### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by pedromxavier** [joaohenriquef/neologismos#1]
Muito legal o projeto! Fui tentar compilar deu isso aqui:
```
src/generator.ts:63:68 - error TS2339: Property 'includes' does not exist on type 'string[]'.

63   const filteredVowels = VOWELS.filter((vowel) => !forbiddenVowels.includes(vowel));
                                                                      ~~~~~~~~


Found 1 error.
```
Eu nunca usei TypeScript, então não saquei muito como corrigir.

**Comment by joaohenrifranco** [comment]
Valeu por testar! 😄

Ainda é bem um rascunho, esforço inicial pra fazer um jogo que usa palavras fakes.

Sobre o erro de compilação, era um problema de configuração do compilador, commitei um fix. Brigado pelo aviso!
